version: '3.8'

services:

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:14.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - acetin-network
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./docker-entrypoint:/docker-entrypoint-initdb.d

          
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    hostname: keycloak
    container_name: keycloak
    restart: unless-stopped
    networks:
      - acetin-network
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8443:8443"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TZ: Europe/Istanbul
      KEYCLOAK_ADMIN: adminadmin
      KC_HTTPS_PORT: "8443"
      PROXY_ADDRESS_FORWARDING: "true"
      KC_DB: postgres
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY: "edge"
      HTTP_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_ADMIN_URL: "https://your_domain.com/admin/keycloak/"
      KC_HOSTNAME_URL: "https://your_domain.com/rest/keycloak/"
      
    volumes:
      - ./my-realm.json:/opt/keycloak/data/import/my-realm.json
      - ./themes:/opt/keycloak/themes
    command:
      - "start-dev" 
      - "--import-realm"

  nginx:
    image: nginx:1.21.4-alpine
    container_name: nginx
    restart: unless-stopped
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./your_ssl.crt:/etc/nginx/your_ssl.crt
      - ./your_ssl.key:/etc/nginx/your_ssl.key
    networks:
      - acetin-network

networks:
  mcc-network:
      name: acetin-network
      driver: bridge
